### ISSUE TITLE
Recomendações

### ISSUE THREAD

**Issue by MarcosBritoSAR** [jowgaze/comandos-git-github#1]
Para cobrir o conteúdo completo do curso, sugiro que adicione os seguintes comandos:

**Comandos de Reset**

-  git reset --soft `<commit>`: **"Retorno Suave, Mantendo Mudanças"**

-  git reset --mixed `<commit>`: **"Retorno ao Passado, Desfazendo o Staging"**

-  git reset --hard `<commit>`: **"Reinício Completo, Descartando Mudanças"**

**Alias**

-  Para criar um alias globalmente: git config --global alias.`<identificador>` ` <comando>`

Uma forma simples de visualizar os *aliases* configurados é usando o seguinte comando: git config --list

**Comment by jowgaze** [comment]
Boa! vou fazer a alteração.
