### ISSUE TITLE
Comando git fetch

### ISSUE THREAD

**Issue by Gabriel-RQ** [jowgaze/comandos-git-github#3]
Acho interessante adicionar também sobre o `git fetch`, que apenas busca pelas mudanças no repositório remoto, sem atualizá-las no repositório local. É útil para quando você apenas precisa verificar a existência de alterações, mas não necessariamente precisa fazer um pull. Alguns editores, como o VSCode, fazem o fetch periodicamente em background para verificar atualizações.

Interessante notar que, o `git pull`, na verdade não passa de um `git fetch` seguido de um `git merge` ou `git rebase` (dependendo das configurações).

Documentação: **https://git-scm.com/docs/git-fetch**

Obs: Pode ser interessante colocar sobre o `git rebase` também.

**Comment by jowgaze** [comment]
Ótima recomendação!
