### ISSUE TITLE
Sugestão de Comando - Cherry-picking

### ISSUE THREAD

**Issue by DouglaSantos777** [jowgaze/comandos-git-github#5]
🍒 **Cherry-picking:**
O cherry-picking é um comando que difere do merge e rebase, que aplicam vários commits de uma vez em outra branch. O comando git cherry-pick permite escolher um commit específico de uma branch e aplicá-lo em outra. Embora seja possível fazer cherry-pick de vários commits, é preferível utilizar o merge nesses casos.

**Comando básico:**

git cherry-pick <commit-hash> 

📜 **Nota: Como aprendemos no curso o hash do commit pode ser encontrado usando o comando.** 

**Se você fizer cherry-pick de uma branch pública, considere usar:**

git cherry-pick -x <commit-hash>

🔍**Links úteis:**

 https://acompiler.com/git-cherry-pick/

obs: Deixando apenas um comando para caso masi gente queria colocar issues aqui kk

**Comment by jowgaze** [comment]
Não conhecia esse! Vou fazer a atualização.
